### ISSUE TITLE
Bug In JAR Wrapper Shell 

### ISSUE THREAD

**Issue by LeStarch** [fprime-community/fpp#104] opened 2021-12-22 19:18 UTC
The JAR shell wrappers that wrap the FPP tools have an error in them:

```
java -jar /Users/mstarch/code/fprime-infra/fpp/fpp-tools/fpp-locate-defs.jar $@
```

Should read as the following (with quotes around `"$@"`:

```
java -jar /Users/mstarch/code/fprime-infra/fpp/fpp-tools/fpp-locate-defs.jar "$@"
```

This informs bash to pass all arguments maintaining the escaping provided by the above call.  Without this, any escaping done in the caller is ignored. This is specifically painful to users with paths that require escaping (e.g.  `/home/user/my code/fprime`) will be broken into two partial paths by the existing code, but should be handled properly by the suggested code.

**Comment by LeStarch** [comment] 2021-12-22 19:19
Note: there is a symmetric error in the CMake integration that was masked by this error.

**Comment by bocchino** [comment] 2021-12-22 21:02
On the FPP side, this is not a bug/oversight. It is a conscious decision not to support path names with spaces in them.

If we want to support path names with spaces, then I think we will need a fair amount of specification, design, implementation, and testing that has not been attempted. For example:

. On the input side
   . What input should fpp-depend see if a user writes `fpp-depend a\ b.fpp c\ d.fpp`?
   . Same question for `fpp-depend "a b.fpp" "c d.fpp"?
   . Same question for `fpp-depend 'a b.fpp' 'c d.fpp'?

. On the output side
   . What should the tools do if a location file has a space in it? e.g., `a b.fpp`? For example, should fpp-depend write out the file as `a b.fpp` or `a\ b.fpp`? If the former, is every tool that uses the output of fpp-depend required to escape spaces before passing them to other tools? Are we doing that? Are we testing the use cases?

As far as I know, we are not using file names with spaces in F Prime. This suggests: (a) we don't need to handle it and (b) we are not testing the relevant use cases. I am not in favor of adding quotation marks to one or two places and hoping/guessing how the rest of it all works.

**Comment by bocchino** [comment] 2021-12-22 21:06
Note that if we put in the quotation marks as suggested, then case (1)(i) should work as one might expect, though I haven't tested it. I don't know what would happen in cases (1)(ii) and (1)(iii). Maybe case (1)(iii) would work reasonably. Case (1)(ii) almost certainly would not.

**Comment by LeStarch** [comment] 2021-12-22 21:41
Within the F´ codebase, I agree, users cannot and should not use files with spaces in them.  However, this is an issue of paths.   If a user places their fprime code in a folder called "my documents" it should work just as well as using "my_documents".

e.g. `/home/myuser/my documents/fprime` can be used by our users and we must support it.  We've seen users do this before and thus far it has worked.

**Comment by bocchino** [comment] 2021-12-22 21:47
I would discourage users from doing that, for the reasons I stated above. Basically, putting spaces in paths is like throwing sand in the works of any shell script. One can make shell scripts robust to this sand-throwing, but we have not attempted to do that in any rigorous or systematic way. For example, I doubt that even the FPP installer script will work if FPP is checked out into a path, because of this:

https://github.com/fprime-community/fpp/blob/ee355fc99eb8040157c62e69f58ac6a8435cd981/compiler/install#L24-L25

I'm pretty certain that the FPP unit test scripts will fail too -- although maybe most users won't care.

If we really want to support paths with spaces, then we need to answer all the questions I posed above and test all the use cases, e.g., FPP checked out in a path with a space, locs files containing spaces, etc.

**Comment by bocchino** [comment] 2021-12-22 21:49
We have to weigh the cost of specifying, implementing, and testing proper support for spaces-in-paths vs. just telling users not to do it. Is there any need to do it, or is it a nice-to-have?

If we don't support it rigorously, then it won't work. Basically the default for any kind of shell script is that it won't work. Making it work right takes effort.

**Comment by bocchino** [comment] 2021-12-22 22:02
> Within the F´ codebase, I agree, users cannot and should not use files with spaces in them.

Also, what's the reason for this distinction? Since we manage dependencies as full paths, it seems like we should either support spaces-in-paths (including filenames) or not. I don't know why we'd need or want to treat paths "inside" F Prime any differently than paths "outside" F Prime.

My assumption when designing and implementing FPP was no spaces in paths, period.

**Comment by bocchino** [comment] 2021-12-22 22:10
It may not take that much work to support spaces in paths, but we should assume it doesn't work unless and until we put in the effort to make it work.

**Comment by bocchino** [comment] 2021-12-22 23:44
Embedded `"` and `'` in path names also clash with standard shell programming assumptions. ':' and ',' cause problems too. There may be others. My suggestion, for simplicity and robustness, is to disallow all these problematic characters. There is an easy workaround, e.g., rename `my project` to `my_project`.

**Comment by bocchino** [comment] 2022-01-07 00:11
Closing this in light of #105, which fixes the immediate issue.

**Closed by bocchino** 2022-01-07 00:11 UTC

**Comment by bocchino** [comment] 2022-01-07 00:15
Continuing the discussion in #109.
